### ISSUE TITLE
Can't find the supplementary information file for the LBFextract paper on bioRxiv

### ISSUE THREAD

**Issue by fei0810** [Isy89/LBF#1]
Hello, I read a paper related to LBF yesterday: https://www.biorxiv.org/content/10.1101/2024.05.03.592314v1

Thank you for developing this excellent tool. I am very interested in several analysis indicators mentioned in the paper, but unfortunately, I did not find the supplementary information files mentioned in the paper on the website.

Perhaps it is not quite appropriate to ask this question here, but I would like to inquire how to obtain the supplementary information files of the paper.

**Comment by Isy89** [comment]
Hi @fei0810 happy to hear about your interest in this tool! The supplementary file will be uploaded in the next days. It should be there by the end of the week. If you have any question feel free to ask at LBFextract@gmail.com.

**Comment by Isy89** [comment]
The supplementary material has just been uploaded. It should be visible to everyone soon.
